# host_vars/lampstack.yml
---

el7_repositories:
  - epel-release

el7_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced

el7_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

