# site.yml
---
- hosts: lampstack
  sudo: true
  roles:
    - bertvv.el7
    - sepolicy
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
    - phpmyadmin

- hosts: webserver
  sudo: true
  roles:
    - bertvv.el7
    - bertvv.httpd
